services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pg_data:
